USE QuanLiThuVien
GO

--Thêm dữ liệu nhà xuất bản
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB01', -- MaNXB - char(10)
          N'Âm nhạc', -- TenNXB - nvarchar(100)
          N'61 Lý Thái Tổ, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB02', -- MaNXB - char(10)
          N'Bản đồ', -- TenNXB - nvarchar(100)
          N'73 Láng Trung, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB03', -- MaNXB - char(10)
          N'Bưu điện', -- TenNXB - nvarchar(100)
          N'18 Nguyễn Du, Hà Nội'  -- DiaChi - nvarchar(100)
          )
 
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB04', -- MaNXB - char(10)
          N'Chính trị Quốc gia', -- TenNXB - nvarchar(100)
          N'22-24 Quang Trung, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB05', -- MaNXB - char(10)
          N'Công an nhân dân', -- TenNXB - nvarchar(100)
          N'167 Mai Hắc Đế, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB06', -- MaNXB - char(10)
          N'Công báo chính phủ', -- TenNXB - nvarchar(100)
          N'1 Bách Thảo, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB07', -- MaNXB - char(10)
          N'Cục Báo chí', -- TenNXB - nvarchar(100)
          N'53A Hàng Chuối, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB08', -- MaNXB - char(10)
          N'Cục xuất bản', -- TenNXB - nvarchar(100)
          N'10 Đường Thành, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB09', -- MaNXB - char(10)
          N'Đại học Bách Khoa', -- TenNXB - nvarchar(100)
          N'Khán đài B, sân vận động Tạ Quang Bửu Đại học Bách Khoa, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB10', -- MaNXB - char(10)
          N'Đại học Kinh tế quốc dân', -- TenNXB - nvarchar(100)
          N'207 Giải Phóng, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB11', -- MaNXB - char(10)
          N'Đại học Hà Nội', -- TenNXB - nvarchar(100)
          N'16 Hàng Chuối, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB13', -- MaNXB - char(10)
          N'Đại học Sư Phạm', -- TenNXB - nvarchar(100)
          N'136 Xuân Thủy Cầu Giấy, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB16', -- MaNXB - char(10)
          N'Giáo dục', -- TenNXB - nvarchar(100)
          N'81 Trần Hưng Đạo, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB20', -- MaNXB - char(10)
          N'Hội nhà văn', -- TenNXB - nvarchar(100)
          N'65 Nguyễn Du, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB21', -- MaNXB - char(10)
          N'Khoa học & Kỹ thuật', -- TenNXB - nvarchar(100)
          N'70 Trần Hưng Đạo, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB22', -- MaNXB - char(10)
          N'Khoa học xã hội', -- TenNXB - nvarchar(100)
          N'61 Phan Chu Trinh, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB23', -- MaNXB - char(10)
          N'Kim Đồng', -- TenNXB - nvarchar(100)
          N'55 Quang Trung, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB24', -- MaNXB - char(10)
          N'Lao động', -- TenNXB - nvarchar(100)
          N'175 Giảng Võ, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB25', -- MaNXB - char(10)
          N'Lao động xã hội', -- TenNXB - nvarchar(100)
          N'41B Lý Thái Tổ, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB26', -- MaNXB - char(10)
          N'Lý luận chính trị', -- TenNXB - nvarchar(100)
          N'56B Quốc Tử Giám, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB27', -- MaNXB - char(10)
          N'Mỹ thuật', -- TenNXB - nvarchar(100)
          N'44B Hàm Long, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB30', -- MaNXB - char(10)
          N'Nông nghiệp', -- TenNXB - nvarchar(100)
          N'D14 Phương Mai, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB31', -- MaNXB - char(10)
          N'Phụ nữ', -- TenNXB - nvarchar(100)
          N'39 Hàng Chuối, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB33', -- MaNXB - char(10)
          N'Quân đội nhân dân', -- TenNXB - nvarchar(100)
          N'23 Lý Nam Đế, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB34', -- MaNXB - char(10)
          N'Sân khấu', -- TenNXB - nvarchar(100)
          N'51 Trần Hưng Đạo, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB35', -- MaNXB - char(10)
          N'Tài chính', -- TenNXB - nvarchar(100)
          N'4 Phan Huy Chú, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB36', -- MaNXB - char(10)
          N'Thanh niên', -- TenNXB - nvarchar(100)
          N'62 Bà Triệu, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB38', -- MaNXB - char(10)
          N'Thế giới', -- TenNXB - nvarchar(100)
          N'46 Trân Hưng Đạo, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB39', -- MaNXB - char(10)
          N'Thể dục Thể thao', -- TenNXB - nvarchar(100)
          N'7 Trịnh Hoài Đức, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB40', -- MaNXB - char(10)
          N'Thông tấn', -- TenNXB - nvarchar(100)
          N'11 Trần Hưng Đạo, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB41', -- MaNXB - char(10)
          N'Thống kê', -- TenNXB - nvarchar(100)
          N'96 Thụy Khê, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB43', -- MaNXB - char(10)
          N'Tôn giáo', -- TenNXB - nvarchar(100)
          N'37 Hùng Vương, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB44', -- MaNXB - char(10)
          N'Tư pháp', -- TenNXB - nvarchar(100)
          N'58-60 Trần Phú, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB46', -- MaNXB - char(10)
          N'Từ điển bách khoa', -- TenNXB - nvarchar(100)
          N'109 Quan Thánh, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB47', -- MaNXB - char(10)
          N'Tri thức', -- TenNXB - nvarchar(100)
          N'45 Nguyễn Du, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB50', -- MaNXB - char(10)
          N'Văn hóa Thông tin', -- TenNXB - nvarchar(100)
          N'43 Lò Đúc, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB51', -- MaNXB - char(10)
          N'Văn học', -- TenNXB - nvarchar(100)
          N'18 Nguyễn Trường Tộ, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB54', -- MaNXB - char(10)
          N'Xây dựng', -- TenNXB - nvarchar(100)
          N'37 Lê Đại Hành, Hà Nội'  -- DiaChi - nvarchar(100)
          )
INSERT dbo.NhaXuatBan
        ( MaNXB, TenNXB, DiaChi )
VALUES  ( 'NXB55', -- MaNXB - char(10)
          N'Y học', -- TenNXB - nvarchar(100)
          N'352 Đội Cấn, Hà Nội'  -- DiaChi - nvarchar(100)
          )
 
 