use QuanLiThuVien
go
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('VH',N'Văn học')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('TC',N'Truyện cười')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('KH',N'Khoa học')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('CTPL',N'Chính trị - Pháp luật')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('VHXH',N'Văn hóa xã hội - Lịch sử')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('TTT',N'Truyện - Tiểu thuyết')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('TT',N'Truyện tranh')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('GT',N'Giáo trình')
insert into TheLoai(MaTheLoai,TenTheLoai)
values ('KT',N'Kinh tế')